replicas: 2
image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
clusterName: es-cluster

caSecret: es-ca
httpSecret: es-http
transportSecret: es-transport

resources:
  requests:
    cpu: "200m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"
